### ISSUE TITLE
Skribbl message should be pinned on creation. 

### ISSUE THREAD

**Issue by burdoto** [comroid-git/Cobalton#19]
Skribbl message should be effectively singleton.

**Comment by peanutbother** [comment]
Why?
What exactly do you expect to be a singleton?
Please reference code.

**Comment by burdoto** [comment]
Only one Skribbl message ever in one server.

Also, this should not occur if message is in any channel of a selectable category

**Comment by peanutbother** [comment]
I would add the option to create a new skribbl
If the command is `c!skribbl new` else return active sessions.

**Comment by peanutbother** [comment]
This is definitely possible if bot stays in session or connects to active sseion to check if it still has people in it, or if session is older than `T` time

**Comment by burdoto** [comment]
?

**Comment by burdoto** [comment]
Moved to https://youtrack.comroid.de/issue/COB-2
