### ISSUE TITLE
Implement Starboard

### ISSUE THREAD

**Issue by burdoto** [comroid-git/Cobalton#2]
# Feature

Starboard is a feature which enables users to mark a message with defined emojiis to promote them on a designated channel, once the minimum amount of those reactions is reached.

**Comment by peanutbother** [comment]
This feature will first be implemented on branch [feature-starboard](../tree/feature-starboard)

**Comment by burdoto** [comment]
Moved to https://youtrack.comroid.de/issue/COB-5
